apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment-stage
  labels:
    app: sample-app-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app-stage
  template:
    metadata:
      labels:
        app: sample-app-stage
    spec:
      containers:
      - name: sample-container
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: TZ
          value: "UTC +530"  # Timezone
        - name: ENVIRONMENT
          value: "stage  # Environment
        - name: LOG_LEVEL
          value: "Info  # Logging level
        - name: DB_HOST
          value: "database-host"  # Database host
        - name: DB_PORT
          value: "5432"  # Database port
        - name: DB_USER
          value: "dbuser  # Database user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sample-deployment-stage
              key: password
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: sample-deployment-stage
      volumes:
      - name: sample-volume
        persistentVolumeClaim:
          claimName: sample-pvc
