apiVersion: v1
kind: Service
metadata:
  name: sample-service-stage
  labels:
    app: sample-app-stage
spec:
  selector:
    app: sample-app-stage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
